Move isDeep and isBoosted from usePools to config files
balancer/frontend-v2 pull request #3094
Opened 2023-03-27 05:42 UTC by timjrobinson

# Description

- Moving the list of deep and boosted pools from the usePools file to individual config files. 

## Type of change

- [x] Code refactor / cleanup

## How should this be tested?

- Ensure that pools that are deep show the correct breakdown of assets on their individual pool page. 
- Ensure pools in the boosted list show their APR correctly with `Boosted APR` in the list. 

## Checklist:

- [x] I have performed a self-review of my own code
- [x] I have requested at least 1 review (If the PR is significant enough, use best judgement here)
- [x] I have commented my code where relevant, particularly in hard-to-understand areas
- [x] If package-lock.json has changes, it was intentional.
- [x] The base of this PR is `master` if hotfix, `develop` if not

2023-03-27 06:27 UTC, agualis requested changes
Looks good but some tests are failing. Tell me if you need support cause some of them are not showing the reason why they fail.

2023-03-27 08:51 UTC, timjrobinson commented
@agualis all fixed. It was becuase tests use goerli config, and the ID's / Addresses of the boosted pool was from Mainnet, which was fine before as the list was the same across all networks but now it's different per network.

2023-03-27 09:32 UTC, agualis approved these changes

2023-03-27 13:56 UTC, garethfuller commented on src/lib/config/goerli/pools.ts
> +    '0x3d5981bdd8d3e49eb7bbdc1d2b156a3ee019c18e', // bb-a-USD2
Duplication.

2023-03-27 14:55 UTC, agualis approved these changes

2023-03-28 08:26 UTC, garethfuller approved these changes

2023-03-28 08:26 UTC, merged