feat: pool risks section in pool page
balancer/frontend-v2 pull request #3359
Opened 2023-05-12 14:01 UTC by agualis

# Description

Adds risks section to pool detail page:

- It has the logic but it does not have text for specific pool risk yet.
- It does not use i18n to simplify the logic (reduce bundle size) until we decide to translate (given that the original `Risks.vue` was not translated neither).

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Dependency changes
- [ ] Code refactor / cleanup
- [ ] Documentation or wording changes
- [ ] Other

## How should this be tested?

Please provide instructions so we can test. Please also list any relevant details for your test configuration.

- [ ] Test A
- [ ] Test B

## Visual context

Please provide any relevant visual context for UI changes or additions. This could be static screenshots or a loom screencast.

## Checklist:

- [ ] I have performed a self-review of my own code
- [ ] I have requested at least 1 review (If the PR is significant enough, use best judgement here)
- [ ] I have commented my code where relevant, particularly in hard-to-understand areas
- [ ] If package-lock.json has changes, it was intentional.
- [ ] The base of this PR is `master` if hotfix, `develop` if not

2023-05-12 14:08 UTC, agualis commented
@pkattera Do we already have specific risks for a some concrete pool?

We should probably add then in a new pool metadata field @gareth?

2023-05-14 14:18 UTC, pkattera commented
@agualis We do not have any specific risks for any pools as far as I know. I thought it may be a good idea to design for this possibility which may arise. We could just start with the category risks and add the ability to add specific risks later if the need arises if it is difficult to set up.

2023-05-15 14:40 UTC, garethfuller requested changes
Because the pool risk page is so large, should we avoid using smooth scroll here? It feels a bit clumsy to click a link to a section on a page and have to wait a non-trivial amount of time for the page to scroll to the right position. wdyt @pkattera?

2023-05-15 14:40 UTC, garethfuller commented on src/pages/pool/_id.vue
> +            <PoolRisks :pool="pool"></PoolRisks>
```suggestion
            <PoolRisks :pool="pool" />
```

2023-05-15 14:44 UTC, garethfuller commented
@pkattera I think we should get this out as is, dependent on review updates above. However, would be nice to make the risk section a little more engaging. @pkattera wdyt about having a bordered box with a relevant icon for each type of risk?

2023-05-15 15:01 UTC, pkattera commented
> Because the pool risk page is so large, should we avoid using smooth scroll here? It feels a bit clumsy to click a link to a section on a page and have to wait a non-trivial amount of time for the page to scroll to the right position. wdyt @pkattera?

I agree that smooth scroll feels clunky when arriving from outside of the page (e.g. clicking from a pool page onto the risks page and then scrolling downwards). Ideally, the user would arrive directly at the anchor when they come from a different page. 

I do like the smooth scroll when clicking anchor links within the risks page. 

Is there an easy fix to allow both behaviors?

2023-05-16 12:38 UTC, garethfuller requested changes
Doesn't work on first load for me: https://www.loom.com/share/5bde7fb3128f4b65a48946dd3b6f4afc

2023-05-16 12:46 UTC, agualis commented
> Doesn't work on first load for me: https://www.loom.com/share/5bde7fb3128f4b65a48946dd3b6f4afc

@ It should work now that I had a delay to wait for the route transition.

2023-05-16 14:37 UTC, garethfuller approved these changes

2023-05-16 14:37 UTC, merged