Move token addresses to the tokens config file
balancer/frontend-v2 pull request #3418
Opened 2023-05-23 12:14 UTC by timjrobinson

# Description

Moves all the token addresses from the contracts file to the tokens file. This is a more correct place for them and they aren't statically defined so the list can be custom to the network instead of having so many empty strings on networks that don't support LSD tokens. 

I also changed a few places referencing "Weth" when really they meant "Wrapped Native Asset". 

## Type of change

- [x] Code refactor / cleanup

## How should this be tested?

- Ensure places involving stETH / stMATIC work as expected. 
- Ensure SOR and other things that might be affected by this work correctly. 

## Checklist:

- [x] I have performed a self-review of my own code
- [x] I have requested at least 1 review (If the PR is significant enough, use best judgement here)
- [x] I have commented my code where relevant, particularly in hard-to-understand areas
- [x] If package-lock.json has changes, it was intentional.
- [x] The base of this PR is `master` if hotfix, `develop` if not

2023-05-23 13:00 UTC, garethfuller requested changes
Thanks for doing this, looks good but a few type/test errors to resolve.

2023-05-24 08:14 UTC, garethfuller reviewed
Tests failing.

2023-05-24 08:21 UTC, agualis commented
> Tests failing.

@timjrobinson 

It was the lido mock. I pushed a commit to fix it. We should replace this untyped vi.mock by a better solution if it fails again.

2023-05-24 10:05 UTC, garethfuller approved these changes

2023-05-24 10:05 UTC, merged